<?php
/**
 * Implements hook_init()
 */
function gofast_microblogging_init() {  
  //Instenciate CKEditor on microblogging
  $blog_path = drupal_get_path('module', 'gofast_microblogging');
  drupal_add_js($blog_path . "/gofast_microblogging.js");
}

/*
 * Implements hook_menu
 */
function gofast_microblogging_menu(){
  $items['blog/add'] = array(
    'page callback' => 'gofast_microblogging_add',
    'access arguments' => array('access content'),
    'access callback' => 'user_access',
    'type' => MENU_NORMAL_ITEM
  );
  $items['blog/update/%'] = array(
    'page callback' => 'gofast_microblogging_update',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'access callback' => 'user_access',
    'type' => MENU_NORMAL_ITEM
  );
  $items['modal/%ctools_js/node/%node/pin-blog'] = array(
    'title' => t('', array(), array('context' => 'gofast')),
    'page callback' => 'gofast_modal_node_pin_content',
    'page arguments' => array(1, 3),
    'access callback' => 'gofast_microblogging_blog_access',
    'access arguments' => array(3),
    'type' => MENU_CALLBACK,
  );
  // Blog (unpublish / publish)
  $items['modal/%ctools_js/node/%node/manage-blog'] = array(
    'title' => 'Manage',
    'page callback' => 'gofast_modal_node_manage',
    'page arguments' => array(1, 3, 5),
    'access callback' => 'gofast_microblogging_blog_access',
    'access arguments' => array(3),
    'type' => MENU_CALLBACK,
  );  
  return $items;
}

function gofast_microblogging_blog_access($node){
  global $user;
  $roles = $user->roles;
  $allowed_roles = ['administrator', 'business administrator'];
  $check = (bool) array_intersect($allowed_roles, $roles);
  return $node->uid == $user->uid || $check;
}

/*
 * Send a blog message
 */
function gofast_microblogging_add($user = NULL, $is_ajax = TRUE){
  $data = $_POST["message"];
  
  //Filter XSS
  $data = gofast_xss_clean($data);
  
  if ($user == NULL){
      global $user;
  }
  
  module_load_include('inc', 'node', 'node.pages');

  $node = new stdClass();
  $node->title = 'Blog message';
  $node->type = 'blog';
  $node->language = LANGUAGE_NONE;
  $node->options = array();
  $node->promote = NODE_NOT_PROMOTED;
  $node->module = 'node';
  $node->comment = COMMENT_NODE_OPEN;
  $node->status = NODE_PUBLISHED;
  $node->uid = $user->uid;
  $node->body[LANGUAGE_NONE][0]['value'] = $data;

  node_save($node);

  //Hack to set the message's parent space ID to 0
  db_insert('og_membership')
  ->fields(array(
    'type' => OG_MEMBERSHIP_TYPE_DEFAULT,
    'etid' => $node->nid,
    'entity_type' => 'node',
    'gid' => '0',
    'group_type' => '0',
    'state' => 1,
    'created' => time(),
    'field_name' => GOFAST_OG_CONTENT_MEMBERSHIP_FIELD,
    'language' => 'und'
  ))
  ->execute();

  $node = node_load($node->nid, NULL, TRUE);
  
  node_access_acquire_grants($node);
  if ($is_ajax){
      print $node->nid;
      exit;
  }
}


function gofast_microblogging_update($blog_id){
    
    module_load_include('inc', 'node', 'node.pages');
    $node = node_load($blog_id);
    $new_blog = $_POST['data'];
    db_update('field_data_body')
	->fields(array('body_value' => $new_blog))
	->condition('entity_id', $blog_id)
	->execute();
    db_update('field_revision_body')
	->fields(array('body_value' => $new_blog))
	->condition('entity_id', $blog_id)
	->execute();
    db_update('node')
	->fields(array('changed' => time()))
	->condition('nid', $blog_id)
	->execute();
    cache_clear_all("field:node:$blog_id", 'cache_field');
    node_load($blog_id,NULL,true);
    
    print 'OK';
    exit;
}