<?php

require_once 'gofast_mail_queue_api.inc';
/*
 * TODO: Document message_formated hook
 */
//
//
/**
 * Implements hook_message_formated
 */
function gofast_mail_queue_message_formated($message){
  //We won't throw a notification if the prevent notify checkbox was checked
  if(!$_POST['prevent_notify']){
    $decoded_message = json_decode($message[0]);
   
    if($decoded_message->node_type == "kanban"){ 
        gofast_mail_queue_api_queue($message, 'message_kanban'); // Queue the message for subscribed users. 
    }elseif($decoded_message->node_type == "kanban_prevent_notify"){
        
    }else{         
        gofast_mail_queue_api_queue($message, 'message'); // Queue the message for subscribed users.
    }
  }
  $_POST['prevent_notify'] = NULL;
}

function gofast_mail_queue_get_items_count(){
  $query = db_select("gofast_mail_queue", "m");
  $count = $query->countQuery()->execute()->fetchField();
  return $count;
}

function gofast_mail_queue_is_smtp_reachable(){
  $mail = new PHPMailer; //The mail object from PHPMailer
  
  //Configure parameters from our configuration
  $mail->isHTML(true);
  $mail->CharSet = "utf-8";
  $mail->isSMTP();
  $mail->SMTPAutoTLS = false; // Disabled TLS (enabled by default) for now
  $mail->SMTPSecure = variable_get('smtp_protocol');
  $mail->Port = variable_get('smtp_port');
  $mail->Host = variable_get('smtp_host');
  $mail->Username = variable_get('smtp_username');
  $mail->Password = variable_get('smtp_password');
  if($mail->Username == "" && $mail->Password == ""){
    $mail->SMTPAuth = false;
  }else{
    $mail->SMTPAuth = true;
  }

  //Try to connect to the SMTP server
  if (!$mail->smtpConnect($mail->SMTPOptions)) {
    return FALSE;
  }
  
  //Close the connexion and validate the test
  $mail->smtpClose();
  return TRUE;
}