<div class="card card-custom ">
    <div class="card-body p-0">
        <div class="pt-0 px-8 pb-4">
            <div class="gutter-b mt-4 d-flex">
                <div class="position-relative GofastUserProfile__picture" style="width:40%">
                    <?php empty($account->picture->filename) ? $filename = "/sites/all/themes/bootstrap-keen/keenv2/assets/media/users/blank.png" : $filename = "/sites/default/files/pictures/" . $account->picture->filename ; ?>
                    <img class="img-responsive h-100px w-100px p-0 symbol symbol-100" src="<?php echo $filename; ?>"></img>
                    <?php if ($self || user_access("gofast administer users")) :?>
                    <div class="position-absolute bottom-0" style="z-index: 1; left: 70px; <?php if ($self || !isset($profile_account_settings)):  ?>margin-right:20px; <?php endif; ?>">
                        <a href="/gofast/nojs/user/edit-avatar/<?= $account->uid ?>" class="ctools-use-modal GofastUserProfile__avatar--icon p-1">
                            <i class="fas fa-pen-square fa-2x p-1"></i>
                        </a>
                    </div>
                    <?php endif; ?>
                </div>
                <div class="w-50 GofastUserProfile__info__name">
                    <div class="font-weight-bolder font-size-h5 text-dark-75 mb-1 d-flex flex-column">
                        <div id="profile-firstname" class="text-hover-primary spinner py-4"><?php // content generated by Drupal.behaviors.gofastUserEditableInputs in gofast_user.js
                                                                                            ?></div>
                        <div id="profile-lastname" class="text-hover-primary"></div>
                        <?php if (!empty($account_blocked)) : ?>
                            <span style="color:#B82010;"><?php echo $account_blocked; ?> </span>
                        <?php endif ?>
                    </div>
                </div>
                <div class="user-profile-menu d-flex justify-content-end">
                    <?php if ($self || isset($profile_account_settings)) : ?>
                        <div class="profile-settings">
                            <div class="profile-account-settings">
                                <?php print $profile_account_settings; ?>
                            </div>
                        </div>

                    <?php endif; ?>
                    <?php if (!empty($contextual_actions)) : ?>
                        <?php print render($contextual_actions); ?>
                    <?php endif; ?>
                </div>
            </div>
            <div class="text-muted mb-1 GofastUserProfile__roleinfo"> <?php print "$profile_roles"; ?></div>
            <div class="pb-3">
                <div class="d-flex justify-content-start">
                </div>
            </div>
            <div class="gutter-b">
                <div class="d-flex align-items-center mb-2">
                    <span class="flex-shrink-0 mr-2 w-25px">
                        <i class="fas fa-award"></i>
                    </span>
                    <div class="text-muted font-weight-bold">
                        <div style="position: relative;">
                            <div style="padding: .5rem;border-radius: .42rem !important;">
                                <div>
                                <?php print $profile_score ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="d-flex align-items-center mb-2">
                    <span class="flex-shrink-0 mr-2 w-25px">
                        <i class="fas fa-phone"></i>
                    </span>
                    <div class="text-muted font-weight-bold">
                        <div class="profile-phone-info spinner py-4">
                        </div>
                    </div>
                </div>
                <div class="d-flex align-items-center mb-2">
                    <span class="flex-shrink-0 mr-2 w-25px">
                        <i class="fas fa-envelope"></i>
                    </span>
                    <div class="text-muted text-hover-primary font-weight-bold" style="width: 90%;">
                        <div class="profile-email-info spinner py-4"></div>
                    </div>
                </div>
                <div class="d-flex align-items-center mb-2">
                    <span class="flex-shrink-0 mr-2 w-25px">
                        <i class="fas fa-briefcase"></i>
                    </span>
                    <div class="d-flex align-items-center">
                        <?php
                        // note that ldap preprocess is still useful for that kind of check
                        if ($a = $self || $is_adm || !empty($ldap['ldap_user_title']['value'])) :
                        ?>
                            <div class="text-muted text-hover-primary font-weight-bold" id="profile-job"></div>
                            <span>@</span>
                        <?php endif; ?>
                        <div class="profile-department-info text-muted text-hover-primary font-weight-bold spinner py-4 "></div>
                    </div>
                </div>
                <?php if ($self || !empty($profile_birthdate)) : ?>
                    <div class="d-flex align-items-center mb-2">
                        <span class="flex-shrink-0 mr-2 w-25px">
                            <i class="fas fa-birthday-cake"></i>
                        </span>
                        <div class="text-muted text-hover-primary font-weight-bold">
                            <div class="profile-birthdate-info spinner py-4"></div>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
            <div class="gutter-b">
                <span class="font-size-md text-muted text-hover-primary font-weight-bold mb-2 d-block text-uppercase"><?php print t('Manager'); ?></span>
                <div class="d-flex align-items-center">
                    <div class="profile-manager-info spinner py-4"></div>
                </div>
            </div>
            <div class="gutter-b">
                <!--begin::Subtitle-->
                <span class="font-size-md text-muted text-hover-primary font-weight-bold mb-2 d-block text-uppercase"><?php print t('My Team'); ?></span>
                <!--end::Subtitle-->
                <div class="profile-team-info symbol-group symbol-hover">
                    <div class="spinner py-4">
                    </div>
                </div>
            </div>
            <div class="gutter-b">
                <!--begin::Subtitle-->
                <span class="font-size-md text-muted text-hover-primary font-weight-bold mb-2 d-block text-uppercase"><?php print t('My relationships'); ?></span>
                <!--end::Subtitle-->
                <div class="profile-relationships-info symbol-group symbol-hover">
                    <div class="spinner py-4">
                    </div>
                </div>
            </div>
            <div class="gutter-b">
                <span class="font-size-md text-muted text-hover-primary font-weight-bold mb-2 d-block text-uppercase"><?php print t('About me'); ?></span>
                <div class="text-muted text-hover-primary font-weight-bold">
                    <div class="profile-description-info spinner py-4"></div>
                </div>
            </div>
            <div class="gutter-b">
                <span class="font-size-md text-muted text-hover-primary font-weight-bold mb-2 d-block text-uppercase" id="skills_id" data-enforce="true" data-vid="<?php print $skills_vid?>"><?php print t('Skills'); ?></span>
                <div class="text-muted text-hover-primary font-weight-bold">
                    <div class="profile-skills-info spinner py-4"></div>
                </div>
            </div>
            <div class="gutter-b">
                <span class="font-size-md text-muted text-hover-primary font-weight-bold mb-2 d-block text-uppercase" id="passions_id" data-enforce="true" data-vid="<?php print $interests_vid?>"><?php print t('Passions'); ?></span>
                <div class="text-muted text-hover-primary font-weight-bold">
                    <div class="profile-passions-info spinner py-4"></div>
                </div>
            </div>
            <div class="gutter-b">
                <span class="font-size-md text-muted text-hover-primary font-weight-bold mb-2 d-block text-uppercase" id="hobbies_id" data-enforce="true" data-vid="<?php print $hobbies_vid?>"><?php print t('Hobbies'); ?></span>
                <div class="text-muted text-hover-primary font-weight-bold">
                    <div class="profile-hobbies-info spinner py-4"></div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    jQuery(document).ready(function() {
        Gofast.user.UserEditableInputs('<?php echo $account->uid; ?>')
        Gofast.load_user_profile_teams();
        Gofast.load_user_profile_spaces();
    });
</script>
